# Generated by Django 4.1 on 2023-08-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iccfixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=25)),
                ('team2', models.CharField(max_length=25)),
                ('date', models.CharField(max_length=25)),
                ('days', models.CharField(max_length=25)),
                ('time', models.CharField(max_length=25)),
                ('venue', models.CharField(max_length=25)),
            ],
        ),
    ]
